### ISSUE TITLE
Instrument does not work with abstract op overload

### ISSUE THREAD

**Issue by serjek** [AlexHaxe/haxe-instrument#11]
Consider you need to apply coverage to this:
```
public static function testOp(a:OpOverload, b:OpOverload):Int {
	return a && b;
}

abstract OpOverload(Bool) from Bool {
	@:op(a && b) static function and(a,b) {
		return a == true ? 1 : 2;
	}
}
``` 
Compiling returns following error: `OpOverload should be Bool` because of this:
**before**
```
{
        return a && b;
}
```
**after**
```
{
        instrument.coverage.CoverageContext.logExpression(459);
        instrument.coverage.CoverageContext.logExpression(460);
        return if ({
                instrument.coverage.CoverageContext.logExpression(464);
                a;
        }) {
                instrument.coverage.CoverageContext.logExpression(462);
                true;
        } else {
                instrument.coverage.CoverageContext.logExpression(463);
                false;
        } && if ({
                instrument.coverage.CoverageContext.logExpression(467);
                b;
        }) {
                instrument.coverage.CoverageContext.logExpression(465);
                true;
        } else {
                instrument.coverage.CoverageContext.logExpression(466);
                false;
        };
}
```
Real life example is `tink.core.Furure.or/and` which we have plenty in a project. I am not sure how to work this around so for now I skip whole function body which produces holes in coverage report.

**Comment by AlexHaxe** [comment]
let me know if my fix works for you.

note: it doesn't address the fact that it won't catch all 4 cases of a boolean expression. for `a && b` coverage will show 100% if `a` and `b` have seen true and false branches individually. 
so one true/true and one false/false invocation will show no missed branches (same goes for true/false and false/true combination).

**Comment by serjek** [comment]
Hey, thanks for the fix! It works better now although will not compile provided that value of `falseExpr` is not always type of `Bool`. Sometimes it may fall into abstract<Bool> like with `coconut.data.Value<Bool>`. Adding `cast false` or same `_instrumentValue` fixes the problem and does not seem to break the test run.
