### ISSUE TITLE
How to instrument a haxelib my application uses ?

### ISSUE THREAD

**Issue by 47rooks** [AlexHaxe/haxe-instrument#18]
I'm trying to get haxe-instrument working on flixel. It does work on my game source but I am having trouble getting it to instrument the libs. My lime project.xml includes this :
```
	<haxeflag name="--macro"
		value='instrument.Instrumentation.profiling(["","flixel"], ["source","..\\..\\.haxelib\\flixel\\5,6,2"], [])' />
	<haxeflag name="-D" value="profiler-console-hierarchy-reporter" />
```
The second entry in each array is for the flixel lib.  I've also tried an absolute path. But when I run this I never get output for flixel code in the reporter. I just see:
```
Executing task: lime test hl -debug  

Instrumenting ..
====================
== Call Hierarchy ==
====================
+ <root> 8152ms
---+ thread-0 8152ms
------+ source/Main.hx:8: Main.new 1 38ms
---------+ source/PlayState.hx:31: PlayState.create 1 6.9999999999999ms
------+ source/PlayState.hx:97: PlayState.update 216 3677ms
---------+ source/PlayState.hx:164: PlayState.ping 3 0ms
---------+ source/PlayState.hx:159: PlayState.hit 3 0ms
```

**Comment by AlexHaxe** [comment]
for things like libraries (e.g. everything not added with `--cp`) you need to use absolute paths to include them.

haxe-instrument uses [PositionTools.toLocation](https://github.com/AlexHaxe/haxe-instrument/blob/5ce5871be21549bb474f806bf169d01bf1914b04/src/instrument/Instrumentation.hx#L277) to get filenames and then does a simple [StringTools.startsWith](https://github.com/AlexHaxe/haxe-instrument/blob/5ce5871be21549bb474f806bf169d01bf1914b04/src/instrument/Instrumentation.hx#L156-L168) comparison, so you will have to use whatever paths that `toLocation` call produces. 
I assume even on Windows it would use slashes instead of backslashes, but I would have to run it on a Windows system to confirm it.

**Comment by 47rooks** [comment]
Ok, so it seems that using slash and an absolute path helps. However I also get compilation issues then. Now this code compiles fine without instrument - in fact I suspect the classes in question are DCEd in normal circumstances though I don't know if that is affected by instrument. Regardless I this :
```
Instrumenting ............................................................................................................................................................................................................................................................................................................/haxe-perf-examples/.haxelib/instrument/1,1,0/src/instrument/Instrumentation.hx:795: characters 4-22 : Cannot return a value from constructor
.../haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/path/FlxPathfinder.hx:78: characters 29-33 : error: flixel.math.FlxPoint should be { copyFrom : flixel.math.FlxPoint -> Unknown<0> }
.../haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/path/FlxPathfinder.hx:78: characters 29-33 : ... have: Array<flixel.math.FlxPoint>
.../haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/path/FlxPathfinder.hx:78: characters 29-33 : ... want: Array<{ copyFrom }>
.../haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/tile/FlxTilemap.hx:922: characters 3-23 : Null<flixel.util.IFlxPooled> should be flixel.math.FlxPoint
.../haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/tile/FlxTilemap.hx:923: characters 3-19 : Null<flixel.util.IFlxPooled> should be flixel.math.FlxPoint
.../haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/system/debug/interaction/tools/Eraser.hx:64: characters 12-16 : Null<{ y : Int, x : Int, width : Int, scrollFactor : Null<Unknown<0>>, isOnScreen : () -> Bool, height : Int }> has no field kill
.../haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/system/debug/interaction/tools/Eraser.hx:66: characters 23-29 : Null<{ y : Int, x : Int, width : Int, scrollFactor : Null<Unknown<0>>, isOnScreen : () -> Bool, height : Int }> should be flixel.FlxBasic
.../haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/system/debug/interaction/tools/Eraser.hx:66: characters 23-29 : ... For function argument 'item'
.../haxe-perf-examples/.haxelib/instrument/1,1,0/src/instrument/Instrumentation.hx:793: characters 8-14 : Variables of type Void are not allowed
```

If it helps the flixel version is 5.6.2. I am using Haxe 4.3.3.

Using various casts I can hack this to work. I don't actually understand why the errors that are reported are as they are. I assumed instrument would just add code into the top and bottom of each function. I didn't expect it would modify the existing code.

But then finally I get this:

```
Instrumenting .........................................................................................................................................................................................................................................................................................................<MYPATH>/haxe-perf-examples/.haxelib/instrument/1,1,0/src/instrument/Instrumentation.hx:795: characters 4-22 : Cannot return a value from constructor
<MYPATH>/haxe-perf-examples/.haxelib/instrument/1,1,0/src/instrument/Instrumentation.hx:793: characters 8-14 : Variables of type Void are not allowed
```
Which I don't understand at all. I believe this is running in macro context which is not my long suit.

Any ideas ?

**Comment by AlexHaxe** [comment]
to measure coverage instrument has to add markers to basically every bit of code, because at any point an exception could disrupt execution. so to make sure a piece of code was covered it needs to have hit all the markers injected into it at least once.

for profiling you need to record entry and exit of function calls. technically it's the top and the bottom of a function - if it's a simple function. as soon as you add `return`'s and `throw`'s you need to make sure to also mark those places, cause they are also exits.

the nature of instrument is such that it adds a build macro to every type / class, which will then add all those markers depending on whether you are profiling, measuring coverage or both. of course instrument doesn't know what types are being used and which aren't. so it adds it's markers to everything that matches your filters.
which includes types that might later get eliminated by DCE, so you might get errors in classes that you might never even heard of.

in some places instrument obviously generates code that introduces compilation errors like the ones you are seeing. which means haxe-instrument might need some fixes to avoid causing those errors.

**Comment by 47rooks** [comment]
Thanx for the details.
Is there any way to see the code it's generating to see what is causing those errors ?
I can describe in detail the test case I am using if you want to check out the errors. None of it yet is my code - it's just a test using a publicly available flixel demo and the production versions of the required libs and of course instrument itself.

**Comment by AlexHaxe** [comment]
I usually use `-D dump=pretty`, but obviously that requires code to compile, so probably won't help in your case.
so that leaves debugging or adding traces and stepping through hundreds of types until you come across the one that is causing issues.

**Comment by 47rooks** [comment]
Ok, as far as I can tell dump=pretty just did nothing, as you expected.
I added prints of the expr in Instrumentation and got this before it spat out the error:

```
expr={pos: #pos(MY_PATH/haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/util/FlxBitmapDataPool.hx:152: characters 3-27), expr: EReturn({pos: #pos(MY_PATH/haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/util/FlxBitmapDataPool.hx:152: characters 10-27), expr: EBinop(OpAssign,{pos: #pos(MY_PATH/haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/util/FlxBitmapDataPool.hx:152: characters 10-19), expr: EConst(<...>)},{pos: #pos(MY_PATH/haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/util/FlxBitmapDataPool.hx:152: characters 22-27), expr: EConst(<...>)})})}

expr={pos: #pos(MY_PATH/haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/util/FlxBitmapDataPool.hx:152: characters 10-27), expr: EBinop(OpAssign,{pos: #pos(MY_PATH/haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/util/FlxBitmapDataPool.hx:152: characters 10-19), expr: EConst(CIdent(maxLength))},{pos: #pos(MY_PATH/haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/util/FlxBitmapDataPool.hx:152: characters 22-27), expr: EConst(CIdent(value))})}

expr={pos: #pos(MY_PATH/haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/util/FlxBitmapDataPool.hx:152: characters 10-19), expr: EConst(CIdent(maxLength))}

expr={pos: #pos(MY_PATH/haxe-perf-examples/.haxelib/flixel/5,6,2/flixel/util/FlxBitmapDataPool.hx:152: characters 22-27), expr: EConst(CIdent(value))}

MY_PATH/haxe-perf-examples/.haxelib/instrument/1,1,0/src/instrument/Instrumentation.hx:795: characters 4-22 : Cannot return a value from constructor
MY_PATH/haxe-perf-examples/.haxelib/instrument/1,1,0/src/instrument/Instrumentation.hx:793: characters 8-14 : Variables of type Void are not allowed
```
Added blank lines for clarify. Now I am not exactly clear but is EConst a constructor or a constant ? Shouldn't be a constant as far as I can tell. Now there is no EConst handler in instrumentExpr(). So I think it's going through EBinop and then has a hernia processing the return statement in FlxBimapDataPool.hx here:

```
	static function set_maxLength(value:Int):Int
	{
		if (maxLength != value)
		{
			var node = _tail;
			while ((node != null) && (length > value))
			{
				var bmd = node.bmd;
				bmd.dispose();
				bmd = null;
				node = node.prev;
				length--;
			}
		}
		return maxLength = value;
	}
```

I don't understand much of what I'm doing so any suggestions greatly appreciated. Will look over the macro tutorials later.

**Comment by 47rooks** [comment]
Ok I've not made much progress so here is my test case:

haxelib list
flixel-demos: [3.1.0]
flixel-tools: [1.5.1]
flixel: [5.6.2]      
instrument: [1.1.0]  
lime: [8.1.2]        
openfl: [9.3.3]      
safety: [1.1.2]

Create the HaxeFlixel Breakout demo with:

```
haxelib run flixel create 
```

Select [04] Breakout from the list

Then modify the Project.xml to contain the following additions to enable the instrument lib:

```
	<haxelib name="instrument" />
	<haxeflag name="--macro"
		value='instrument.Instrumentation.profiling(["", "flixel"], ["source","<ABS_PATH_TO_HAXELIB>/.haxelib/flixel/5,6,2"], [])' />
	<haxeflag name="-D" value="profiler-console-hierarchy-reporter" />
	<haxeflag name="-D" value="dump=pretty" />
```
Run 
```
lime test hl -debug
```
Of course that requires hashlink - I'm using 1.14. I haven't tried cpp but I expect it's the same. The other thing of note perhaps is that I'm on Win 10 though again I don't think it's getting far enough for that to be the issue but of course I don't know.

My main obstacle right now is that I cannot figure out how the errors relate to the macro transformed code - I cannot see that code and debug prints haven't so far been revealing.

**Comment by 47rooks** [comment]
Ok, I think most of the problems stem from the `return cast result;` in Instrumentation.replaceReturn. Removing the cast almost works. There are two additional cases that then arise in another class (BMFontInfo.hx) where I have to introduce casts to compensate. So I don't know exactly the change needed here.  This is due to some anonymous structs which specify Int elements but which are instantiated with Null<Int>values. But in order to see if I can get it all running before coming up with a complete PR I'm left trying to solve:

```
MY_PATH/haxe-perf-examples/.haxelib/instrument/1,1,0/src/instrument/Instrumentation.hx:824: characters 5-18 
: Cannot return a value from constructor
MY_PATH/haxe-perf-examples/.haxelib/instrument/1,1,0/src/instrument/Instrumentation.hx:821: characters 9-15 
: Variables of type Void are not allowed
```
The line numbers are not quite right because of my debug in the module.
Any suggestions on how to track these down ?

Oh I see that the master branch has different code here. I'll try using that and see if it's better.

**Comment by 47rooks** [comment]
Ok the latest on master worked better but still has problems with Flixel. I will raise other issues for those so as not to create confusion.

FlxColor inline issue : https://github.com/AlexHaxe/haxe-instrument/issues/19
Type mismatch on structure returns : https://github.com/AlexHaxe/haxe-instrument/issues/20

**Comment by 47rooks** [comment]
Closing as other issues cover the problems with using the latest version with HaxeFlixel.

**Comment by AlexHaxe** [comment]
thanks for taking the time to dive into these issues! I will setup a test project and try to figure out how to fix those (and maybe others that might pop up)

**Comment by AlexHaxe** [comment]
I managed to get my flixel [same game clone](https://github.com/AlexHaxe/haxe-same/) to compile with full coverage and profiling enabled on flixel library using #22 branch (I had to add `["flixel.system.macros"]` as excludes for coverage to make it work). and currently you have to do coverage and profiling or just profiling to make it compile.
I'll look into running a coverage only setup.

Haxe nightly also doesn't work, it seems to choke on haxeui and openfl stuff, which shouldn't be included in / affected by instrumentation, but somehow is?!

obviously my small game uses only limited parts of flixel, so your experience might be different but maybe give #22 a try to see if my changes improve support for flixel.

**Comment by 47rooks** [comment]
Ok, just tried these out on instrument 1.2 after reinstalling flixel 5.6.2 to remove my hacks and w/a. Then ran a vanilla instrument without any excludes. Worked fine for all the issues I opened recently. Many thanx for this.
