### ISSUE TITLE
Abstract 'this' value can only be modified inside an inline function in HaxeFlixel

### ISSUE THREAD

**Issue by 47rooks** [AlexHaxe/haxe-instrument#19]
Following on from https://github.com/AlexHaxe/haxe-instrument/issues/18.

Using Haxe 4.3.3
Instrument git at 5ce5871be21549bb474f806bf169d01bf1914b04
flixel 5.6.2

FlxColor is an abstract which uses a lot of inline functions that assign to `this`.
Similar to https://github.com/AlexHaxe/haxe-instrument/issues/2 there are a lot of build issues in FlxColor.hx because of this. I worked around them using @:ignoreInstrument metadata but could not apply it just to the abstract it seems. I have to apply it method by method. Once I did that it got to compile. 

But it appears the fix merged for issue 2 does not address these cases.

**Comment by AlexHaxe** [comment]
should be fixed in 1.2.0
