### ISSUE TITLE
This modifier in abstract inline method

### ISSUE THREAD

**Issue by benmerckx** [AlexHaxe/haxe-instrument#2]
I have a setter on an abstract that reassigns `this`. Since instrument disables inlining it fails to profile with:
````
Abstract 'this' value can only be modified inside an inline function
````

**Comment by AlexHaxe** [comment]
I will have to build a small test case and experiment on how I can circumvent that.

adding `@:ignoreProfiler` or `@:ignoreInstrument` to your abstract type should exclude it from instrumentation as a temporary workaround (or excluding it from your init `--macro` call)

**Comment by benmerckx** [comment]
All I can think of is stepping through the expressions and detecting it, but that seems a little complicated with the differents binops that can modify. Maybe @:ignore_ should exist on a field level for these cases?

**Comment by AlexHaxe** [comment]
removing inline was / is a workaround for similiar issues, obviously that doesn't solve all issues or even creates new ones...

> Maybe @:ignore_ should exist on a field level for these cases?

sounds like a good idea regardless of `this` issue, e.g for excluding a very noisy function
