### ISSUE TITLE
Cannot return `null` from Void-function

### ISSUE THREAD

**Issue by Aidan63** [AlexHaxe/haxe-instrument#3]
Hello,
Ran into another issue and I'm not quite sure how to recreate it yet so I don't have a concise example. I get the following error output to the console twice when trying to compile my test suite with coverage reporting.

```
C:/Users/AidanLee/AppData/Roaming/haxe/haxe_libraries/instrument/1.0.0/github/93376539f78c96ab5ca5f75a3b588b3c4cc95593/src/instrument/Instrumentation.hx:396: characters 32-48 : Cannot return `null` from Void-function
../../src/lib/uk/aidanlee/flurry/api/gpu/geometry/UniformBlob.hx:17: lines 17-88 : Defined in this class
```
I've posted the `UniformBlob` class below which starts at lines 17 and goes to 88. I've tried removing the dependencies of that class and putting it in a standalone project but I haven't been able to re-create the error yet. I'm using the buddy test lib but I'm not sure if thats related as removing the package the UniformBlob class is from allows everything to compile and run fine.

(I've stripped comments, imports, etc from this class so its shorter, nothing too complex going on with it though)
```haxe
class UniformBlob
{
    public final id : ResourceID;

    public final name : String;

    public final buffer : BufferData;

    final locations : Map<String, Int>;

    public function new(_name : String, _buffer : BufferData, _locations : Map<String, Int>)
    {
        id        = Hash.uniqueHash();
        name      = _name;
        buffer    = _buffer;
        locations = _locations;
    }

    public function setMatrix(_name : String, _matrix : Matrix)
    {
        if (locations.exists(_name))
        {
            final byteOffset = buffer.byteOffset + locations[_name].unsafe();
            final byteMatrix = (_matrix : BufferData);

            buffer.bytes.blit(byteOffset, byteMatrix.bytes, byteMatrix.byteOffset, 64);
        }
    }

    public function setVector4(_name : String, _vector : Vector4)
    {
        if (locations.exists(_name))
        {
            final byteOffset = buffer.byteOffset + locations[_name].unsafe();
            final byteVector = (_vector : BufferData);

            buffer.bytes.blit(byteOffset, byteVector.bytes, byteVector.byteOffset, 16);
        }
    }
}
```
I'll keep having a poke around and see if I can get a small example, but I thought I'd post the issue now incase you have any ideas.

**Comment by AlexHaxe** [comment]
I believe latest 1.2.0 should also fix this issue. feel free to reopen or create a new one should you find a new instance of that bug (hopefully) with a more reproducible demo project.
