### ISSUE TITLE
Null safety errors when instrumentation macro is used

### ISSUE THREAD

**Issue by Aidan63** [AlexHaxe/haxe-instrument#4]
When compiling with null safety enabled you will start to get compiler errors even if you've checked for null values. The following is based on an example from the haxe manual null safety page.

```haxe
package tests;

class Main {
	static function main() {
        func({ field : 'hello' });
    }
    
    static function func(o : { field:Null<String> }) {
        if (o.field != null) {
            trace(o.field.length);
        }
    }
}
```
```
-cp src
-L instrument
-D coverage-console-summary-reporter
-main tests.Main
--macro nullSafety("tests", Strict)
--macro instrument.Instrumentation.coverage(['tests'], ['src'], [])
--interp
```

The above gives the following error `src/tests/Main.hx:10: characters 19-33 : Null safety: Cannot access "length" of a nullable value.` but removing the coverage macro line from the hxml or changing the null safety mode to `Off` will allow everything to compile fine.

**Comment by AlexHaxe** [comment]
can you check if my latest changes work for you?

instrument will now remove any `@:nullSafety` metadata from types and fields. when running instrumentation checking for correct handling of null values is not a primary concern, so I think it is acceptable to turn it off.

**Comment by Aidan63** [comment]
Yep, just tried it out and my null safety enabled code is compiling and running fine now!

**Comment by AlexHaxe** [comment]
thanks for testing!

I've just uploaded a new 1.1.0 release to haxelib.
