### ISSUE TITLE
Excluding sub packages

### ISSUE THREAD

**Issue by Aidan63** [AlexHaxe/haxe-instrument#5]
Request this time!
It doesn't currently seem possible to include a package and then specify a sub package of that to exclude. The exclude meta data for types doesn't work in my case as the sub package I want to exclude includes libraries which aren't compiled with the test suite.
The work around I've done for now is to manually include all the other sub packages instead of the top level one, not ideal though as it makes for a very long hxml line and I need to remember to include any new sub packages.
Cheers.

**Comment by AlexHaxe** [comment]
`instrument.Instrumentation.coverage` and `instrument.Instrumentation.profiling` init macros now accept either an array of strings or a single string representing a filename. each file should contain one entry per line (expects `\n` as linebreak character, `\r\n` should also work). entries are trimmed for whitespace. 

type names ("`packagename`.`typename`") are matched against include and exclude entries using `startsWith` (exclude beats include). field names ("`packagename`.`typename`.`fieldname`") match against excludes, allow exclusion of individual fields.

it's probably not a perfect solution, but in a more complex scenario you could use files that are auto-generated by a previous build step to make sure you don't miss new sub packages.
